global:
  scrape_interval: 15s  # Default interval
  evaluation_interval: 15s  # How often to evaluate rules
  external_labels:
    monitor: 'go-micro-monitor'

scrape_configs:
  - job_name: 'order'
    scrape_interval: 5s
    static_configs:
      - targets: ['order-service:9092']  # Using service name instead of static IP

#  - job_name: 'jaeger'
#    scrape_interval: 10s
#    static_configs:
#      - targets: [ 'jaeger:16686' ]
#
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: [ 'localhost:9090' ]
#
#  - job_name: 'grafana'
#    static_configs:
#      - targets: [ 'grafana:3000' ]